const   listFamiliers = [ 
    {  
        nom : "Mobelin",
        type : "Herbivore",
        favori : "Brochette",
        zone : "Forêt tropicale de Sabada",
        numéro : 1,
        element : "Feu:6-Foudre:4"
    ,
        logo : "../../assets/img/pet/MobelinLogo.png",
        detail : "../../assets/img/pet/MobelinDetails.PNG",
},
    {  
        nom : "Mobelin bleu",
        attribut : "Symbiose",
        type : "Herbivore",
        favori : "Ragoût de viande simple",
        zone : "Forêt tropicale de Sabada",
        numéro : 2,
        element : "Givre:6-Terre:4"
    ,
        logo : "../../assets/img/pet/Mobelin bleuLogo.png",
        detail : "../../assets/img/pet/Mobelin bleuDetails.PNG",
},
    {  
        nom : "Marmotte",
        attribut : "Assistance",
        type : "Herbivore",
        favori : "Brochette",
        zone : "Forêt tropicale de Sabada",
        numéro : 3,
        element : "Terre:6-Foudre:4"
    ,
        logo : "../../assets/img/pet/MarmotteLogo.png",
        detail : "../../assets/img/pet/MarmotteDetails.PNG",
},
    {  
        nom : "Marmotte de tonnerre",
        attribut : "Assistance",
        type : "Herbivore",
        favori : "Ragoût de viande aux légumes sauvages",
        zone : "Gorge de Chiwawa",
        numéro : 4,
        element : "Foudre:6-Feu:4"
    ,
        logo : "../../assets/img/pet/Marmotte de tonnerreLogo.png",
        detail : "../../assets/img/pet/Marmotte de tonnerreDetails.PNG",
},
    {  
        nom : "Marmotte de feu",
        attribut : "Assistance",
        type : "Herbivore",
        favori : "Brochette végétarienne",
        zone : "Forêt tropicale de Sabada",
        numéro : 5,
        element : "Feu:6-Foudre:4"
    ,
        logo : "../../assets/img/pet/Marmotte de feuLogo.png",
        detail : "../../assets/img/pet/Marmotte de feuDetails.PNG",
},
    {  
        nom : "Marmotte enneigée",
        attribut : "Assistance",
        type : "Herbivore",
        favori : "Brochette végétarienne",
        zone : "Gorge de Chiwawa",
        numéro : 6,
        element : "Givre:6-Terre:4"
    ,
        logo : "../../assets/img/pet/Marmotte enneigéeLogo.png",
        detail : "../../assets/img/pet/Marmotte enneigéeDetails.PNG",
},
    {  
        nom : "Smilodon",
        attribut : "ATQ",
        type : "Bête",
        favori : "Généreux plateau grillé",
        zone : "Forêt tropicale de Sabada",
        numéro : 7,
        element : "Terre:6-Foudre:4"
    ,
        logo : "../../assets/img/pet/SmilodonLogo.png",
        detail : "../../assets/img/pet/SmilodonDetails.PNG",
},
    {  
        nom : "Grenouille à ventre rond",
        attribut : "Symbiose",
        type : "Aquatique",
        favori : "Plateau de sashimi",
        zone : "Côte de Bababo",
        numéro : 8,
        element : "Terre:6-Givre:4"
    ,
        logo : "../../assets/img/pet/Grenouille à ventre rondLogo.png",
        detail : "../../assets/img/pet/Grenouille à ventre rondDetails.PNG",
},
    {
        nom : "???", //Grenouille nageoire
        attribut : "Symbiose",
        type : "",
        favori : "Ragoût de légumes sauvage",
        zone : "Côte Nord-est (continent de foudre",
        numéro : 9,
        element : "Eau:6-Feu:4"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {  
        nom : "Gorille-licorne",
        attribut : "Gardien",
        type : "Herbivore",
        favori : "Jue de fruit",
        zone : "Forêt tropicale de Sabada",
        numéro : 10,
        element : "Foudre:5-Terre:5"
    ,
        logo : "../../assets/img/pet/Gorille-licorneLogo.png",
        detail : "../../assets/img/pet/Gorille-licorneDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 11,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {  
        nom : "Lainergie",
        attribut : "Guardien",
        type : "Herbivore",
        favori : "Brochette végétarienne",
        zone : "Forêt tropicale de Sabada",
        numéro : 12,
        element : "Terre:6-Foudre:4"
    ,
        logo : "../../assets/img/pet/LainergieLogo.png",
        detail : "../../assets/img/pet/LainergieDetails.PNG",
},
    {  
        nom : "Lainergie à cornes spiralées",
        attribut : "Guardien",
        type : "Herbivore",
        favori : "Doux comme du miel",
        zone : "Glacier de Pucketa",
        numéro : 13,
        element : "Terre:4-Givre:6"
    ,
        logo : "../../assets/img/pet/Lainergie à cornes spiraléesLogo.png",
        detail : "../../assets/img/pet/Lainergie à cornes spiraléesDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 14,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 15,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {  
        nom : "Ornithorynque",
        attribut : "Symbiose",
        type : "Aquatique",
        favori : "Jus de fruit",
        zone : "Forêt tropicale de Sabada",
        numéro : 16,
        element : "Terre:5-Givre:5"
    ,
        logo : "../../assets/img/pet/OrnithorynqueLogo.png",
        detail : "../../assets/img/pet/OrnithorynqueDetails.PNG",
},
    {  
        nom : "Raptor",
        attribut : "ATQ",
        type : "Dragon terre",
        favori : "oeuf au plat",
        zone : "Cote de Cobo",
        numéro : 17,
        element : "Feu:7-Foudre:3"
    ,
        logo : "../../assets/img/pet/RaptorLogo.png",
        detail : "../../assets/img/pet/RaptorDetails.PNG",
},
    {
        nom : "Pissenlit",
        attribut : "Assistance",
        type : "",
        favori : "???",
        zone : "mille-Aiguilles",
        numéro : 18,
        element : "Foudre:5-Terre:5"
    ,
        logo : "../../assets/img/pet/PissenlitLogo.png",
        detail : "../../assets/img/pet/PissenlitDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 19,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {  
        nom : "Ratel",
        attribut : "ATQ",
        type : "Herbivore",
        favori : "Mélasse",
        zone : "Forêt tropicale de Sabada",
        numéro : 20,
        element : "Foudre:5-Terre:5"
    ,
        logo : "../../assets/img/pet/RatelLogo.png",
        detail : "../../assets/img/pet/RatelDetails.PNG",
},
    
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 21,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {  
        nom : "Prérosaure agile",
        attribut : "ATQ",
        type : "Volant",
        favori : "Brochette",
        zone : "Forêt tropicale de Sabada",
        numéro : 22,
        element : "Givre:6-Terre:4"
    ,
        logo : "../../assets/img/pet/Prérosaure agileLogo.png",
        detail : "../../assets/img/pet/Prérosaure agileDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 23,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "Pangolin",
        attribut : "Gardien",
        type : "Bête",
        favori : "Truffes à la côte",
        zone : "Mille Aiguilles",
        numéro : 24,
        element : "Terre:6-Foudre:4"
    ,
        logo : "../../assets/img/pet/PangolinLogo.png",
        detail : "../../assets/img/pet/PangolinDetails.PNG",
},
    {  
        nom : "Mobelin noir",
        attribut : "Symbiose",
        type : "Herbivore",
        favori : "Ragoût de viande aux légumes sauvages",
        zone : "Gorge de Chiwawa",
        numéro : 25,
        element : "Terre:7-Foudre:3"
    ,
        logo : "../../assets/img/pet/Mobelin noirLogo.png",
        detail : "../../assets/img/pet/Mobelin noirDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 26,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {  
        nom : "Dragon acaudal",
        attribut : "Guardien",
        type : "Fragon terre",
        favori : "Ragout de viande aux legumes sauvages",
        zone : "Gorge de chiwawa",
        numéro : 27,
        element : "Feu:7-Foudre:3"
    ,
        logo : "../../assets/img/pet/Dragon acaudalLogo.png",
        detail : "../../assets/img/pet/Dragon acaudalDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 28,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???", //Chouette Blanche
        attribut : "Symbiose",
        type : "???",
        favori : "Potage aux légumes sauvages",
        zone : "???",
        numéro : 29,
        element : "Givre:6-Terre:4"
     ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "Eperon",
        attribut : "ATQ",
        type : "Volant",
        favori : "Sashimi de calmar",
        zone : "Met de Rabo",
        numéro : 30,
        element : "Terre:6-Givre:4"
    ,
        logo : "../../assets/img/pet/EperonLogo.png",
        detail : "../../assets/img/pet/EperonDetails.PNG",
},
    {  
        nom : "Brontosaure",
        attribut : "ATQ",
        type : "Volant",
        favori : "Porc aigre-doux",
        zone : "Desert de Bata",
        numéro : 31,
        element : "Foudre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/BrontosaureLogo.png",
        detail : "../../assets/img/pet/BrontosaureDetails.PNG",
},
    {  
        nom : "Tricératops de tonnerre",
        attribut : "Guardien",
        type : "Dragon terre",
        favori : "Jus de fruit",
        zone : "Forêt tropicale de Sabada",
        numéro : 32,
        element : "Foudre:7-Feu:3"
    ,
        logo : "../../assets/img/pet/Tricératops de tonnerreLogo.png",
        detail : "../../assets/img/pet/Tricératops de tonnerreDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 33,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "Dragon couronne de roche",
        attribut : "Symbiose",
        type : "Dragon Terre",
        favori : "Combat de fruits et légumes",
        zone : "Désert de Cora",
        numéro : 34,
        element : "Foudre:4-Terre:6"
    ,
        logo : "../../assets/img/pet/Dragon couronne de rocheLogo.png",
        detail : "../../assets/img/pet/Dragon couronne de rocheDetails.PNG",
},
    {  
        nom : "Chameau",
        attribut : "Assistance",
        type : "Herbivore",
        favori : "Legumes frits au chili",
        zone : "Desert de Bata",
        numéro : 35,
        element : "Terre:7-Foudre:3"
    ,
        logo : "../../assets/img/pet/ChameauLogo.png",
        detail : "../../assets/img/pet/ChameauDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 36,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {  
        nom : "Morse",
        attribut : "Symbiose",
        type : "Aquatique",
        favori : "Plate de sashimi",
        zone : "Cote de Bababo",
        numéro : 37,
        element : "Givre:6-Terre:4"
    ,
        logo : "../../assets/img/pet/MorseLogo.png",
        detail : "../../assets/img/pet/MorseDetails.PNG",
},
    {  
        nom : "Poisson-globe",
        attribut : "Symbiose",
        type : "Aquatique",
        favori : "Plateau de sashimi",
        zone : "Cote de Bababo",
        numéro : 38,
        element : "Terre:7-Givre:3"
    ,
        logo : "../../assets/img/pet/Poisson-globeLogo.png",
        detail : "../../assets/img/pet/Poisson-globeDetails.PNG",
},
    {  
        nom : "Tortue",
        attribut : "Guardien",
        type : "Aquatique",
        favori : "Brochette de fruits de mer",
        zone : "Cote de bababo",
        numéro : 39,
        element : "Terre:5-Givre:5"
    ,
        logo : "../../assets/img/pet/TortueLogo.png",
        detail : "../../assets/img/pet/TortueDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 40,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {  
        nom : "Rapasdepic poilu",
        attribut : "ATQ",
        type : "Volant",
        favori : "Brochette de fruits de mer",
        zone : "Cote de Bababo",
        numéro : 41,
        element : "Givre:6-Terre:4"
    ,
        logo : "../../assets/img/pet/Rapasdepic poiluLogo.png",
        detail : "../../assets/img/pet/Rapasdepic poiluDetails.PNG",
},
    {  
        nom : "Alcidé",
        attribut : "Assistance",
        type : "Volant",
        favori : "Sashimi du guerrier",
        zone : "Fjord de Horu",
        numéro : 42,
        element : "Givre:6-Terre:4"
    ,
        logo : "../../assets/img/pet/AlcidéLogo.png",
        detail : "../../assets/img/pet/AlcidéDetails.PNG",
},
    {
    nom : "Tigre blanc",
    attribut : "ATQ",
    type : "Bete",
    favori : "Porc aigre-doux",
    zone : "Volcan Jujule",
    numéro : 43,
    element : "Givre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Tigre blancLogo.png",
        detail : "../../assets/img/pet/Tigre blancDetails.PNG",
},
    {
    nom : "Grenouille ronde de flammes",
    attribut : "Symbiose",
    type : "Aquatique",
    favori : "Brochette de fruits de mer",
    zone : "Volcan Jujule",
    numéro : 44,
    element : "Feu:7-Givre:3"
    ,
        logo : "../../assets/img/pet/Grenouille ronde de flammesLogo.png",
        detail : "../../assets/img/pet/Grenouille ronde de flammesDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 45,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
    nom : "Ankylosaure osseux",
    attribut : "Guardien",
    type : "Dragon Terre",
    favori : "Ragout de radis",
    zone : "Volcan Jujule",
    numéro : 46,
    element : "Givre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Ankylosaure osseuxLogo.png",
        detail : "../../assets/img/pet/Ankylosaure osseuxDetails.PNG",
},
    {
    nom : "Bete de lave en chef",
    attribut : "Guardien",
    type : "Bete",
    favori : "Ragout de viande simple",
    zone : "Volcan Jujule",
    numéro : 47,
    element : "Feu:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/Bete de lave en chefLogo.png",
        detail : "../../assets/img/pet/Bete de lave en chefDetails.PNG",
},
    {
    nom : "Écureuil volant",
    attribut : "Assistance",
    type : "Volant",
    favori : "Fromage grille au miel",
    zone : "Volcan Jujule",
    numéro : 48,
    element : "Terre:6-Foudre:4"
    ,
        logo : "../../assets/img/pet/Écureuil volantLogo.png",
        detail : "../../assets/img/pet/Écureuil volantDetails.PNG",
},
    {
    nom : "Marmotte céleste",
    attribut : "Assistance",
    type : "Herbivore",
    favori : "Brochette de champignons",
    zone : "Foret tropical de sinbad",
    numéro : 49,
    element : "Terre:7-Givre:3"
    ,
        logo : "../../assets/img/pet/Marmotte célesteLogo.png",
        detail : "../../assets/img/pet/Marmotte célesteDetails.PNG",
},
    {
    nom : "Marmotte coup-de-foudre",
    attribut : "Assistance",
    type : "Herbivore",
    favori : "Legumes frit au chili",
    zone : "Forte tropicale de sinbad",
    numéro : 50,
    element : "Foudre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Marmotte coup-de-foudreLogo.png",
        detail : "../../assets/img/pet/Marmotte coup-de-foudreDetails.PNG",
},
    {
    nom : "Marmotte volante de feu",
    attribut : "Assistance",
    type : "Herbivore",
    favori : "Brochette de champignons",
    zone : "Foret tropicale de sinbad",
    numéro : 51,
    element : "Feu:7-Foudre:3"
    ,
        logo : "../../assets/img/pet/Marmotte volante de feuLogo.png",
        detail : "../../assets/img/pet/Marmotte volante de feuDetails.PNG",
},
    {
    nom : "Marmotte volante de givre",
    attribut : "Assistance",
    type : "Jerbivore",
    favori : "Brochette de champignons",
    zone : "Foret tropicale de sinbad",
    numéro : 52,
    element : "Givre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Marmotte volante de givreLogo.png",
        detail : "../../assets/img/pet/Marmotte volante de givreDetails.PNG",
},
    {
    nom : "T.rex",
    attribut : "ATQ",
    type : "Dragon terre",
    favori : "Genereux plateau grille",
    zone : "Foret tropicale de Sabada",
    numéro : 53,
    element : "Feu:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/T.rexLogo.png",
        detail : "../../assets/img/pet/T.rexDetails.PNG",
},
    {
    nom : "Smilodon alpha",
    attribut : "ATQ",
    type : "Bete",
    favori : "Banquet de chef inegale",
    zone : "Plaine de toto",
    numéro : 54,
    element : "Terre:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/Smilodon alphaLogo.png",
        detail : "../../assets/img/pet/Smilodon alphaDetails.PNG",
},
    {
    nom : "Gorille-licorne en chef",
    attribut : "Symbiose",
    type : "Herbivore",
    favori : "Sauce au citron et au miel",
    zone : "Plaines de toto",
    numéro : 55,
    element : "Givre:8-Feu:2"
    ,
        logo : "../../assets/img/pet/Gorille-licorne en chefLogo.png",
        detail : "../../assets/img/pet/Gorille-licorne en chefDetails.PNG",
},
    {
    nom : "Yak blanc",
    attribut : "Symbiose",
    type : "Herbivore",
    favori : "Ragout de radis",
    zone : "Plaines de toto",
    numéro : 56,
    element : "Givre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Yak blancLogo.png",
        detail : "../../assets/img/pet/Yak blancDetails.PNG",
},
    {
    nom : "Ours brun et roux",
    attribut : "Symbiose",
    type : "Bete",
    favori : "Sauce au citron et au miel",
    zone : "Plaines de toto",
    numéro : 57,
    element : "Feu:7-Givre:3"
    ,
        logo : "../../assets/img/pet/Ours brun et rouxLogo.png",
        detail : "../../assets/img/pet/Ours brun et rouxDetails.PNG",
},
    {
    nom : "Stégosaure",
    attribut : "Guardien",
    type : "Dragon terre",
    favori : "Oeuf au plat",
    zone : "cote de cobo",
    numéro : 58,
    element : "Terre:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/StégosaureLogo.png",
        detail : "../../assets/img/pet/StégosaureDetails.PNG",
},
    {
    nom : "Raptor blanc",
    attribut : "ATQ",
    type : "Dragon terre",
    favori : "Genereux plateau grille",
    zone : "Foret tropicale de Sabada",
    numéro : 59,
    element : "Givre:7-Feu:3"
    ,
        logo : "../../assets/img/pet/Raptor blancLogo.png",
        detail : "../../assets/img/pet/Raptor blancDetails.PNG",
},
    {
    nom : "Ptérosaure alpha",
    attribut : "Symbiose",
    type : "Volant",
    favori : "Oeuf au plat",
    zone : "Cote de cobo",
    numéro : 60,
    element : "Feu:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/Ptérosaure alphaLogo.png",
        detail : "../../assets/img/pet/Ptérosaure alphaDetails.PNG",
},
    {
    nom : "Tortue géante",
    attribut : "Guardien",
    type : "Aquatique",
    favori : "Poisson cuit dans les feuilles de lotus",
    zone : "Cote de cobo",
    numéro : 61,
    element : "Givre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Tortue géanteLogo.png",
        detail : "../../assets/img/pet/Tortue géanteDetails.PNG",
},
    {
    nom : "Ankylosaure de feu",
    attribut : "Guardien",
    type : "Dragon terre",
    favori : "Milkshake mystique",
    zone : "Fjord de hori",
    numéro : 62,
    element : "Feu:7-Foudre:3"
    ,
        logo : "../../assets/img/pet/Ankylosaure de feuLogo.png",
        detail : "../../assets/img/pet/Ankylosaure de feuDetails.PNG",
},
    {
    nom : "Kingura",
    attribut : "Guardien",
    type : "Aquatique",
    favori : "Poisson cuit dans des feuilles de lotus",
    zone : "Fjord de hori",
    numéro : 63,
    element : "Givre:6-Terre:4"
    ,
        logo : "../../assets/img/pet/KinguraLogo.png",
        detail : "../../assets/img/pet/KinguraDetails.PNG",
},
    {
    nom : "Crabe de roche",
    attribut : "Guardien",
    type : "Aquatique",
    favori : "Poisson cuit dans des feuilles de lotus",
    zone : "Fjord de Hori",
    numéro : 64,
    element : "Terre:7-Givre:3"
    ,
        logo : "../../assets/img/pet/Crabe de rocheLogo.png",
        detail : "../../assets/img/pet/Crabe de rocheDetails.PNG",
},
    {
    nom : "Rhinocéros à lame en chef",
    attribut : "Symbiose",
    type : "Bete",
    favori : "Milkshake mystique",
    zone : "Fjord de Hori",
    numéro : 65,
    element : "Foudre:8-Feu:2"
    ,
        logo : "../../assets/img/pet/Rhinocéros à lame en chefLogo.png",
        detail : "../../assets/img/pet/Rhinocéros à lame en chefDetails.PNG",
},
    {
    nom : "Stégosaure de lave",
    attribut : "Guardien",
    type : "Dragon terre",
    favori : "Pot-au-feu",
    zone : "Grotte de glace de tintin",
    numéro : 66,
    element : "Feu:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/Stégosaure de laveLogo.png",
        detail : "../../assets/img/pet/Stégosaure de laveDetails.PNG",
},
    {
    nom : "Dragon d'Éole",
    attribut : "ATQ",
    type : "Volant",
    favori : "Pot-au-feu",
    zone : "Grotte de glace de tintin",
    numéro : 67,
    element : "Terre:7-Foudre:3"
    ,
        logo : "../../assets/img/pet/Dragon d'ÉoleLogo.png",
        detail : "../../assets/img/pet/Dragon d'ÉoleDetails.PNG",
},
    {
    nom : "Vélociraptor polaire",
    attribut : "Assistance",
    type : "Dragon terre",
    favori : "Pot-au-feu",
    zone : "Grotte de glace de tintin",
    numéro : 68,
    element : "Givre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Vélociraptor polaireLogo.png",
        detail : "../../assets/img/pet/Vélociraptor polaireDetails.PNG",
},
    {
    nom : "Corythosaure",
    attribut : "Symbiose",
    type : "Dragon terre",
    favori : "Ragout de radis",
    zone : "Grotte de glace de tintin",
    numéro : 69,
    element : "Givre:6-Terre:4"
    ,
        logo : "../../assets/img/pet/CorythosaureLogo.png",
        detail : "../../assets/img/pet/CorythosaureDetails.PNG",
},
    {
    nom : "Dodo des plaine enneigées",
    attribut : "ATQ",
    type : "Volant",
    favori : "Sashimi de marlin",
    zone : "Terre enneigees de tovana",
    numéro : 70,
    element : "Givre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Dodo des plaine enneigéesLogo.png",
        detail : "../../assets/img/pet/Dodo des plaine enneigéesDetails.PNG",
},
    {
    nom : "Yak blanc alpha",
    attribut : "Symbiose",
    type : "Herbivore",
    favori : "Milkshake mystique",
    zone : "Terres enneigees de tovana",
    numéro : 71,
    element : "Givre:8-Terre:2"
    ,
        logo : "../../assets/img/pet/Yak blanc alphaLogo.png",
        detail : "../../assets/img/pet/Yak blanc alphaDetails.PNG",
},
    {
    nom : "Ours polaire en chef",
    attribut : "Guardien",
    type : "Bete",
    favori : "Sashimi de marlin",
    zone : "Terre enneigees de tovana",
    numéro : 72,
    element : "Givre:8-Terre:2"
    ,
        logo : "../../assets/img/pet/Ours polaire en chefLogo.png",
        detail : "../../assets/img/pet/Ours polaire en chefDetails.PNG",
},
    {
    nom : "Rhinocéros à lame",
    attribut : "Symbiose",
    type : "Bete",
    favori : "Sashimi de marlin",
    zone : "Terre enneigees de tovana",
    numéro : 73,
    element : "Foudre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Rhinocéros à lameLogo.png",
        detail : "../../assets/img/pet/Rhinocéros à lameDetails.PNG",
},
    {
    nom : "Tétraodon polaire",
    attribut : "Symbiose",
    type : "Aquatique",
    favori : "Soupe de coquilles asint jacques aux legumes sauvages",
    zone : "Glacier de puck",
    numéro : 74,
    element : "Givre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Tétraodon polaireLogo.png",
        detail : "../../assets/img/pet/Tétraodon polaireDetails.PNG",
},
    {
    nom : "Vargr alpha",
    attribut : "ATQ",
    type : "Bete",
    favori : "Cotes de porc au barbecue",
    zone : "Glacier de puck",
    numéro : 75,
    element : "Terre:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/Vargr alphaLogo.png",
        detail : "../../assets/img/pet/Vargr alphaDetails.PNG",
},
    {
    nom : "Lézard à collerette",
    attribut : "Assistance",
    type : "Dragon terre",
    favori : "Cuisse de bete en pot",
    zone : "Glacier de puck",
    numéro : 76,
    element : "Givre:6-Terre:4"
    ,
        logo : "../../assets/img/pet/Lézard à colleretteLogo.png",
        detail : "../../assets/img/pet/Lézard à colleretteDetails.PNG",
},
    {
    nom : "Lezard à collerette en chef",
    attribut : "ATQ",
    type : "Dragon terre",
    favori : "Cuisse de bete en pot",
    zone : "Glacier de puck",
    numéro : 77,
    element : "Givre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Lezard à collerette en chefLogo.png",
        detail : "../../assets/img/pet/Lezard à collerette en chefDetails.PNG",
},
    {
    nom : "Mobelin rouge en chef",
    attribut : "Symbiose",
    type : "Herbivore",
    favori : "Curry de viande de chef",
    zone : "Montagne enneigee de dodori",
    numéro : 78,
    element : "Feu:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/Mobelin rouge en chefLogo.png",
        detail : "../../assets/img/pet/Mobelin rouge en chefDetails.PNG",
},
    {
    nom : "Loup blanc alpha",
    attribut : "ATQ",
    type : "Bete",
    favori : "Curry de viande de chef",
    zone : "Montagne enneigee de dodori",
    numéro : 79,
    element : "GivrE:8-Feu:2"
    ,
        logo : "../../assets/img/pet/Loup blanc alphaLogo.png",
        detail : "../../assets/img/pet/Loup blanc alphaDetails.PNG",
},
    {
    nom : "Renard polaire",
    attribut : "Assistance",
    type : "Bete",
    favori : "Curry de viance de chef",
    zone : "Montagne enneigee de dodori",
    numéro : 80,
    element : "Givre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Renard polaireLogo.png",
        detail : "../../assets/img/pet/Renard polaireDetails.PNG",
},
    {
    nom : "Ours brun",
    attribut : "Symbiose",
    type : "Bete",
    favori : "Assiette de viandes grillees",
    zone : "Montagne enneigee de dodori",
    numéro : 81,
    element : "Terre:7-Foudre:3"
    ,
        logo : "../../assets/img/pet/Ours brunLogo.png",
        detail : "../../assets/img/pet/Ours brunDetails.PNG",
},
    {
    nom : "Dodo",
    attribut : "ATQ",
    type : "Vlant",
    favori : "Gala de crevettes",
    zone : "Bois de sinvasa",
    numéro : 82,
    element : "Feu:7-Foudre:3"
    ,
        logo : "../../assets/img/pet/DodoLogo.png",
        detail : "../../assets/img/pet/DodoDetails.PNG",
},
    {
    nom : "Dragon reine",
    attribut : "ATQ",
    type : "Volant",
    favori : "Gala de crevette",
    zone : "Bois de sinvasa",
    numéro : 83,
    element : "Givre:10"
    ,
        logo : "../../assets/img/pet/Dragon reineLogo.png",
        detail : "../../assets/img/pet/Dragon reineDetails.PNG",
},
    {
    nom : "Ours polaire",
    attribut : "Symbiose",
    type : "Bete",
    favori : "Gala de crevette",
    zone : "Bois de sinvasa",
    numéro : 84,
    element : "Givre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Ours polaireLogo.png",
        detail : "../../assets/img/pet/Ours polaireDetails.PNG",
},
    {
    nom : "Araignée timide",
    attribut : "Assistance",
    type : "Aquatique",
    favori : "Doux comme du miel",
    zone : "Bois de sinvasa",
    numéro : 85,
    element : "Foudre:7-Feu:3"
    ,
        logo : "../../assets/img/pet/Araignée timideLogo.png",
        detail : "../../assets/img/pet/Araignée timideDetails.PNG",
},
    {
    nom : "Mammouth",
    attribut : "Symbiose",
    type : "Bete",
    favori : "Declinaison de fruits",
    zone : "Fjord de horu",
    numéro : 86,
    element : "Terre:9-Givre:1"
    ,
        logo : "../../assets/img/pet/MammouthLogo.png",
        detail : "../../assets/img/pet/MammouthDetails.PNG",
},
    {
    nom : "Demétrodon",
    attribut : "Symbiose",
    type : "Dragon terre",
    favori : "Declinaison de fruits",
    zone : "Fjord de horu",
    numéro : 87,
    element : "Terre:7-Givre:3"
    ,
        logo : "../../assets/img/pet/DemétrodonLogo.png",
        detail : "../../assets/img/pet/DemétrodonDetails.PNG",
},
    {
    nom : "Dimétrodon de foudre",
    attribut : "Symbiose",
    type : "Dragon terre",
    favori : "Declinaison de fruit",
    zone : "Fjord de horu",
    numéro : 88,
    element : "Foudre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Dimétrodon de foudreLogo.png",
        detail : "../../assets/img/pet/Dimétrodon de foudreDetails.PNG",
},
    
    {
        nom : "Poisson Bouclier",
        attribut : "Gardien",
        type : "???",
        favori : "Shanhai Brûlant",
        zone : "La cascade",
        numéro : 89,
        element : "Foudre:8-Terre:2"
    ,
        logo : "../../assets/img/pet/Poisson BouclierLogo.png",
        detail : "../../assets/img/pet/Poisson BouclierDetails.PNG",
},
    {
    nom : "Brontosaure argyroptère",
    attribut : "ATQ",
    type : "Volant",
    favori : "Sashimi du guerrier",
    zone : "Glacier de Pucketa",
    numéro : 90,
    element : "Foudre:8-Feu:2"
    ,
        logo : "../../assets/img/pet/Brontosaure argyroptèreLogo.png",
        detail : "../../assets/img/pet/Brontosaure argyroptèreDetails.PNG",
},
    {
    nom : "Dragon de Rochenoire",
    attribut : "Gardien",
    type : "Dragon terre",
    favori : "Porc aigre doux",
    zone : "Désert de bata",
    numéro : 91,
    element : "Terre:7-Foudre:3"
    ,
        logo : "../../assets/img/pet/Dragon de RochenoireLogo.png",
        detail : "../../assets/img/pet/Dragon de RochenoireDetails.PNG",
},
    {
    nom : "Dragon acaudal de lumière pâle",
    attribut : "Gardien",
    type : "Dragon terre",
    favori : "Sashimi du guerrier",
    zone : "Glacier de pucketa",
    numéro : 92,
    element : "Givre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Dragon acaudal de lumière pâleLogo.png",
        detail : "../../assets/img/pet/Dragon acaudal de lumière pâleDetails.PNG",
},
    {
    nom : "Ours noir",
    attribut : "Symbiose",
    type : "Bête",
    favori : "Doux comme du miel",
    zone : "Glacier de pucketa",
    numéro : 93,
    element : "Foudre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Ours noirLogo.png",
        detail : "../../assets/img/pet/Ours noirDetails.PNG",
},
    {
    nom : "tigre blanc alpha",
    attribut : "ATQ",
    type : "Bête",
    favori : "Assiette de viandes grillees",
    zone : "Bois de warry",
    numéro : 94,
    element : "Givre:8-Terre:2"
    ,
        logo : "../../assets/img/pet/tigre blanc alphaLogo.png",
        detail : "../../assets/img/pet/tigre blanc alphaDetails.PNG",
},
    {
    nom : "Ankylosaure",
    attribut : "Gardien",
    type : "Dragon terre",
    favori : "Soupe de coquilles saint jacques aux legumes sauvages",
    zone : "Bois de warry",
    numéro : 95,
    element : "Terre:7-Foudre:3"
    ,
        logo : "../../assets/img/pet/AnkylosaureLogo.png",
        detail : "../../assets/img/pet/AnkylosaureDetails.PNG",
},
    {
    nom : "Rhicocéros",
    attribut : "Symbiose",
    type : "Bête",
    favori : "Soupe de coquilles saint jacques aux legumes sauvages",
    zone : "Bois de warry",
    numéro : 96,
    element : "Givre:6-Terre:4"
    ,
        logo : "../../assets/img/pet/RhicocérosLogo.png",
        detail : "../../assets/img/pet/RhicocérosDetails.PNG",
},
    {
    nom : "Renard de foudre",
    attribut : "Assistance",
    type : "Herbivore",
    favori : "Melasse",
    zone : "Foret tropicale de sabada",
    numéro : 97,
    element : "Foudre:8-Feu:2"
    ,
        logo : "../../assets/img/pet/Renard de foudreLogo.png",
        detail : "../../assets/img/pet/Renard de foudreDetails.PNG",
},
    {
    nom : "Tuk-tuk de feu",
    attribut : "Assistance",
    type : "Volant",
    favori : "Crabe thermidor",
    zone : "Cote de totori",
    numéro : 98,
    element : "Feu:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/Tuk-tuk de feuLogo.png",
        detail : "../../assets/img/pet/Tuk-tuk de feuDetails.PNG",
},
    {
    nom : "Strique cristatelle",
    attribut : "Assistance",
    type : "Volcan",
    favori : "Takoyaki",
    zone : "Cote de totori",
    numéro : 99,
    element : "Foudre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/Strique cristatelleLogo.png",
        detail : "../../assets/img/pet/Strique cristatelleDetails.PNG",
},
    {
    nom : "Moa géant",
    attribut : "Assistance",
    type : "Bête",
    favori : "Takoyaki",
    zone : "Cote de totori",
    numéro : 100,
    element : "Feu:9-Givre:1"
    ,
        logo : "../../assets/img/pet/Moa géantLogo.png",
        detail : "../../assets/img/pet/Moa géantDetails.PNG",
},
    {
    nom : "Placoderme de Clace",
    attribut : "Gardien",
    type : "Aquatique",
    favori : "Takoyaki",
    zone : "Côte de totori",
    numéro : 101,
    element : "Givre:8-Feu:2"
    ,
        logo : "../../assets/img/pet/Placoderme de ClaceLogo.png",
        detail : "../../assets/img/pet/Placoderme de ClaceDetails.PNG",
},
    {
    nom : "Dragon de lunevent",
    attribut : "Assistance",
    type : "Volant",
    favori : "Crabe thernidor",
    zone : "Désert de Girka",
    numéro : 102,
    element : "Givre:9-Feu:1"
    ,
        logo : "../../assets/img/pet/Dragon de luneventLogo.png",
        detail : "../../assets/img/pet/Dragon de luneventDetails.PNG",
},
    {
    nom : "Renard du desert",
    attribut : "Assistance",
    type : "Herbivore",
    favori : "Viande cuite dans des feuilles de lotus",
    zone : "Desert de girka",
    numéro : 103,
    element : "Terre:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/Renard du desertLogo.png",
        detail : "../../assets/img/pet/Renard du desertDetails.PNG",
},
    {
    nom : "Lézard à collerette en chef",
    attribut : "ATQ",
    type : "Dragon terre",
    favori : "Viande cuite dans des feuilles de lotus",
    zone : "Deset de girka",
    numéro : 104,
    element : "Terre:7-Foure:3"
    ,
        logo : "../../assets/img/pet/Lézard à collerette en chefLogo.png",
        detail : "../../assets/img/pet/Lézard à collerette en chefDetails.PNG",
},
    {
    nom : "Lézard à collerette solaire",
    attribut : "Assistance",
    type : "Dragon terre",
    favori : "Viande cuite dans feuilles de lotus",
    zone : "Deset de girka",
    numéro : 105,
    element : "Feu:7-Foudre:3"
    ,
        logo : "../../assets/img/pet/Lézard à collerette solaireLogo.png",
        detail : "../../assets/img/pet/Lézard à collerette solaireDetails.PNG",
},
    
    {
        nom : "Élan irlandais",
        attribut : "Assistance",
        type : "Herbivore",
        favori : "Shanhai pot épicé",
        zone : "Oasis de Palu",
        numéro : 106,
        element : "Terre:9-Foudre:1"
    ,
        logo : "../../assets/img/pet/Élan irlandaisLogo.png",
        detail : "../../assets/img/pet/Élan irlandaisDetails.PNG",
},
    {
    nom : "Chameau blanc",
    attribut : "Assistance",
    type : "Herbivore",
    favori : "Melange de legumes sauvages",
    zone : "Oasis de Paro",
    numéro : 107,
    element : "Givre:8-Terre:2"
    ,
        logo : "../../assets/img/pet/Chameau blancLogo.png",
        detail : "../../assets/img/pet/Chameau blancDetails.PNG",
},
    {
    nom : "Pélican",
    attribut : "Symbiose",
    type : "Volant",
    favori : "Crabe termidor",
    zone : "Givre:7-Terre:3",
    numéro : 108,
    element : "Givre:7-Terre:3"
    ,
        logo : "../../assets/img/pet/PélicanLogo.png",
        detail : "../../assets/img/pet/PélicanDetails.PNG",
},
    
    {
        nom : "Bernard-l’ermite",
        attribut : "Aquatique",
        type : "Gardien",
        favori : "mer et montagne épicé",
        zone : "Oasis de Paro",
        numéro : 109,
        element : "Terre:8-Givre:2"
    ,
        logo : "../../assets/img/pet/Bernard-l’ermiteLogo.png",
        detail : "../../assets/img/pet/Bernard-l’ermiteDetails.PNG",
},
    {
        nom : "Coup de Foudre",
        attribut : "Gardien",
        type : "Dragon Terre",
        favori : "Légumes sauvages intégrés",
        zone : "Lac salé de Karusa",
        numéro : 110,
        element : "Foudre:9-Feu:1"
    ,
        logo : "../../assets/img/pet/Coup de FoudreLogo.png",
        detail : "../../assets/img/pet/Coup de FoudreDetails.PNG",
},
    {
        nom : "???",
        attribut : "Herbivore",
        type : "Symbiose",
        favori : "Mélange de légumes sauvages",
        zone : "Lac salé de Karusa",
        numéro : 111,
        element : "Foudre:3-Terre:7"
    ,
        logo : "../../assets/img/pet/Yack AlphaLogo.png",
        detail : "../../assets/img/pet/Yack AlphaDetails.PNG",
},
    {
        nom : "Gerboise d’eau",
        attribut : "Herbivore",
        type : "Assistance",
        favori : "Mer et montagne épicé",
        zone : "Lac Salé de Karusa",
        numéro : 112,
        element : "Foudre:3-Terre:7"
    ,
        logo : "../../assets/img/pet/Gerboise d’eauLogo.png",
        detail : "../../assets/img/pet/Gerboise d’eauDetails.PNG",
},
    {
        nom : "Placoderme de roche",
        attribut : "Aquatique",
        type : "Gardien",
        favori : "Ragout de la mer",
        zone : "Lac salé de Karusa",
        numéro : 113,
        element : "Terre:8-Givre:2"
    ,
        logo : "../../assets/img/pet/Placoderme de rocheLogo.png",
        detail : "../../assets/img/pet/Placoderme de rocheDetails.PNG",
},
    {
    nom : "Roi à crinière",
    attribut : "Symbiose",
    type : "Herbivore",
    favori : "Ragout de viande simple",
    zone : "Foret tropicale de Sabada",
    numéro : 114,
    element : "Terre:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/Roi à crinièreLogo.png",
        detail : "../../assets/img/pet/Roi à crinièreDetails.PNG",
},
    {
        nom : "Brontosaure chrysoptère",
        attribut : "Volant",
        type : "ATQ",
        favori : "Ragout de la mer",
        zone : "Mille-aiguilles",
        numéro : 115,
        element : "Feu:1-Foudre:9"
    ,
        logo : "../../assets/img/pet/Brontosaure chrysoptèreLogo.png",
        detail : "../../assets/img/pet/Brontosaure chrysoptèreDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 116,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "Tricéraptops",
        attribut : "Dragon Terre",
        type : "Gardien",
        favori : "Ragout de la mer",
        zone : "Mille-Aiguilles",
        numéro : 117,
        element : "Foudre:3-Terre:7"
    ,
        logo : "../../assets/img/pet/TricéraptopsLogo.png",
        detail : "../../assets/img/pet/TricéraptopsDetails.PNG",
},
    {
    nom : "T.Rex de Rochenoire",
    attribut : "ATQ",
    type : "Dragon terre",
    favori : "Cuisse de bete en pot",
    zone : "Gorge de chiwawa",
    numéro : 118,
    element : "Terre:8-Givre:2"
    ,
        logo : "../../assets/img/pet/T.Rex de RochenoireLogo.png",
        detail : "../../assets/img/pet/T.Rex de RochenoireDetails.PNG",
},
    {
        nom : "Dragon des montagnes",
        attribut : "Dragon terre",
        type : "Gardien",
        favori : "Côtes de porc au barbecue",
        zone : "Montagne de gros-caillou",
        numéro : 119,
        element : "Foudre:4-Terre:6"
    ,
        logo : "../../assets/img/pet/Dragon des montagnesLogo.png",
        detail : "../../assets/img/pet/Dragon des montagnesDetails.PNG",
},
    {
        nom : "Dragon des montagnier géant",
        attribut : "dragon terre",
        type : "Gardien",
        favori : "Côtes de porc au barbecue",
        zone : "Montagne de Gros-caillou",
        numéro : 120,
        element : "Foudre:4-Terre:6"
    ,
        logo : "../../assets/img/pet/Dragon des montagnier géantLogo.png",
        detail : "../../assets/img/pet/Dragon des montagnier géantDetails.PNG",
},
    {
        nom : "Radobaan",
        attribut : "Dragon Terre",
        type : "Gardien",
        favori : "Roti de jarret",
        zone : "Montagne de Gros-caillou",
        numéro : 121,
        element : "Terre:8-Givre:2"
    ,
        logo : "../../assets/img/pet/RadobaanLogo.png",
        detail : "../../assets/img/pet/RadobaanDetails.PNG",
},
    {
        nom : "Dragon-Typhon",
        attribut : "Volant",
        type : "ATQ",
        favori : "Curry de Crabe épicé",
        zone : "Désert de Cora",
        numéro : 122,
        element : "Terre:2-Givre:8"
    ,
        logo : "../../assets/img/pet/Dragon-TyphonLogo.png",
        detail : "../../assets/img/pet/Dragon-TyphonDetails.PNG",
},
    {
    nom : "Dragon-tyran",
    attribut : "ATQ",
    type : "Dragon terre",
    favori : "Banquet de chef inegale",
    zone : "Foret tropicale de sinbad",
    numéro : 123,
    element : "Feu:10"
    ,
        logo : "../../assets/img/pet/Dragon-tyranLogo.png",
        detail : "../../assets/img/pet/Dragon-tyranDetails.PNG",
},
    {
    nom : "Panda roux",
    attribut : "Assistance",
    type : "Bete",
    favori : "Legume frits au chili",
    zone : "Desert de bata",
    numéro : 124,
    element : "Feu:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/Panda rouxLogo.png",
        detail : "../../assets/img/pet/Panda rouxDetails.PNG",
},
    
    {
        nom : "Pangolin en chef",
        attribut : "Bête",
        type : "Gardien",
        favori : "Banquet de chef inégalé",
        zone : "Désert de Cora",
        numéro : 125,
        element : "Foudre:3-Terre:7"
    ,
        logo : "../../assets/img/pet/Pangolin en chefLogo.png",
        detail : "../../assets/img/pet/Pangolin en chefDetails.PNG",
},
    {
        nom : "Raptor Noir",
        attribut : "Dragon terre",
        type : "ATQ",
        favori : "Curry de crabe épicé",
        zone : "Oasis de Papeto",
        numéro : 126,
        element : "Foudre:3-Terre:7"
    ,
        logo : "../../assets/img/pet/Raptor NoirLogo.png",
        detail : "../../assets/img/pet/Raptor NoirDetails.PNG",
},
    {
        nom : "Colibri argenté",
        attribut : "Volant",
        type : "Assistance",
        favori : "Assiette de fruits et légumes",
        zone : "Oasis de Papeto",
        numéro : 127,
        element : "Terre:3-Givre:7"
    ,
        logo : "../../assets/img/pet/Colibri argentéLogo.png",
        detail : "../../assets/img/pet/Colibri argentéDetails.PNG",
},
    {
        nom : "Vargr Blanc",
        attribut : "Bête",
        type : "Assistance",
        favori : "Délices de la mer de Shashimi",
        zone : "Oasis de Papeto",
        numéro : 128,
        element : "Terre:3-Givre:7"
    ,
        logo : "../../assets/img/pet/Vargr BlancLogo.png",
        detail : "../../assets/img/pet/Vargr BlancDetails.PNG",
},
    {
        nom : "Protodragon",
        attribut : "Dragon terre",
        type : "Gardien",
        favori : "Curry de crabe épicé",
        zone : "Oasis de Papeto",
        numéro : 129,
        element : "Terre:10"
    ,
        logo : "../../assets/img/pet/ProtodragonLogo.png",
        detail : "../../assets/img/pet/ProtodragonDetails.PNG",
},
    {
        nom : "Dragon lion de Glace",
        attribut : "Volant",
        type : "ATQ",
        favori : "Cuisine a se damner",
        zone : "Lac salé des Gyséens",
        numéro : 130,
        element : "Terre:2-Givre:8"
    ,
        logo : "../../assets/img/pet/Dragon lion de GlaceLogo.png",
        detail : "../../assets/img/pet/Dragon lion de GlaceDetails.PNG",
},
    {
        nom : "oiseau cui-cui",
        attribut : "Volant",
        type : "Assistance",
        favori : "Côtes de porc assaisonés aux truffes",
        zone : "Montagne de Gros-caillou",
        numéro : 131,
        element : "Foudre:2-Terre:8"
    ,
        logo : "../../assets/img/pet/oiseau cui-cuiLogo.png",
        detail : "../../assets/img/pet/oiseau cui-cuiDetails.PNG",
},
    {
        nom : "Ornithorynque furieux",
        attribut : "Aquatique",
        type : "ATQ",
        favori : "Cuisine à se damner",
        zone : "Lac Salé des Gyséens",
        numéro : 132,
        element : "Feu:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/Ornithorynque furieuxLogo.png",
        detail : "../../assets/img/pet/Ornithorynque furieuxDetails.PNG",
},
    {
        nom : "Aiguille de mer",
        attribut : "Dragon terre",
        type : "Symbiose",
        favori : "Délices de la mer de Shashimi",
        zone : "Lac salé des Gyséens",
        numéro : 133,
        element : "Terre:1-Givre:9"
    ,
        logo : "../../assets/img/pet/Aiguille de merLogo.png",
        detail : "../../assets/img/pet/Aiguille de merDetails.PNG",
},
    {
    nom : "???", //T.rex de foudre
    attribut : "ATQ",
    type : "dragon terre",
    favori : "Assiette de viandes grillees",
    zone : "Bois de warry",
    numéro : 134,
    element : "Foudre:8-Terre:2"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 135,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 136,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 137,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 138,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 139,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???", //Oiseau dudu
        attribut : "Symbiose",
        type : "???",
        favori : "cotelettes et truffes",
        zone : "Montagne Boulder",
        numéro : 140,
        element : "Terre:8-Foudre:2"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 141,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "Morse en chef",
        attribut : "Aquatique",
        type : "Gardien",
        favori : "Cuisine à se damner",
        zone : "Cote des chutes géantes",
        numéro : 142,
        element : "Terre:1-Givre:9"
    ,
        logo : "../../assets/img/pet/Morse en chefLogo.png",
        detail : "../../assets/img/pet/Morse en chefDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 143,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 144,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "Ecureuil volant de foudre",
        attribut : "Volant",
        type : "Assistance",
        favori : "Délices de la mer en sashimi",
        zone : "Lac salé des Gyséens",
        numéro : 145,
        element : "Feu:3-Foudre:7"
    ,
        logo : "../../assets/img/pet/Ecureuil volant de foudreLogo.png",
        detail : "../../assets/img/pet/Ecureuil volant de foudreDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 146,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro :147,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 148,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
    nom : "Ours brun et roux en chef",
    attribut : "Guardien",
    type : "Bete",
    favori : "Melasse",
    zone : "Foret tropicale de sabada",
    numéro : 149,
    element : "Feu:8-Givre:2"
    ,
        logo : "../../assets/img/pet/Ours brun et roux en chefLogo.png",
        detail : "../../assets/img/pet/Ours brun et roux en chefDetails.PNG",
},
    {
    nom : "???",
    attribut : "???",
    type : "???",
    favori : "???",
    zone : "???",
    numéro : 150,
    element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 151,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 152,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 153,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "Loup roux alpha",
        attribut : "Bête",
        type : "Symbiose",
        favori : "Cotes de porc assaisonnées aux truffes",
        zone : "Désert de Cora",
        numéro : 154,
        element : "Feu:9-Foudre:1"
    ,
        logo : "../../assets/img/pet/Loup roux alphaLogo.png",
        detail : "../../assets/img/pet/Loup roux alphaDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 155,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 156,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 157,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 158,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 159,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 160,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 161,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 162,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 163,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 164,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 165,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 166,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 167,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 168,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 169,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 170,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 171,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "Petit Narval",
        attribut : "Symbiose",
        type : "Aquatique",
        favori : "Coquille Saint-Jacques Rotie",
        zone : "Côte des chutes géantes",
        numéro : 172,
        element : "Terre:3-Givre:7"
    ,
        logo : "../../assets/img/pet/Petit NarvalLogo.png",
        detail : "../../assets/img/pet/Petit NarvalDetails.PNG",
},
    {
        nom : "Narval alpha de tonnerre",
        attribut : "Symbiose",
        type : "Aquatique",
        favori : "oeuf à la vapeur et fruits de mer",
        zone : "Mer de Rabo",
        numéro : 173,
        element : "Foudre:8-Terre2"
    ,
        logo : "../../assets/img/pet/Narval alpha de tonnerreLogo.png",
        detail : "../../assets/img/pet/Narval alpha de tonnerreDetails.PNG",
},
    {
        nom : "Lièvre de mer bleu",
        attribut : "Assistance",
        type : "Aquatique",
        favori : "Oeuf à Vapeur et fruits de mer",
        zone : "Côte des chutes géantes",
        numéro : 174,
        element : "Terre:3-Givre:7"
    ,
        logo : "../../assets/img/pet/Lièvre de mer bleuLogo.png",
        detail : "../../assets/img/pet/Lièvre de mer bleuDetails.PNG",
},
    {
        nom : "Lièvre de mer blanc",
        attribut : "Assistance",
        type : "Aquatique",
        favori : "Oeuf à Vapeur et fruits de mer",
        zone : "Côte des chutes géantes",
        numéro : 175,
        element : "Terre:3-Givre:7"
    ,
        logo : "../../assets/img/pet/Lièvre de mer blancLogo.png",
        detail : "../../assets/img/pet/Lièvre de mer blancDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 176,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "Hippocampe des vases",
        attribut : "Assistance",
        type : "Aquatique",
        favori : "Coquille saint jacques rotie",
        zone : "Mer de Rabo",
        numéro : 177,
        element : "Terre:7-Givre:3"
    ,
        logo : "../../assets/img/pet/Hippocampe des vasesLogo.png",
        detail : "../../assets/img/pet/Hippocampe des vasesDetails.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 178,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 179,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 180,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "???",
        type : "???",
        favori : "???",
        zone : "???",
        numéro : 181,
        element : "???"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???", //Foudre Assistance
        attribut : "Volant",
        type : "Assistance",
        favori : "Aucun (avec une Dragon-Ball ou top 1 saison)",
        zone : "Lac salé des Gyséens",
        numéro : 182,
        element : "Foudre:8-Terre:2"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "Volant",
        type : "???",
        favori : "Aucun (avec une Dragon-Ball ou top 1 saison)",
        zone : "Lac salé des Gyséens",
        numéro : 183,
        element : "Foudre:8-Terre:2"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "???",
        attribut : "Volant",
        type : "???",
        favori : "Aucun (avec une Dragon-Ball ou top 1 saison)",
        zone : "Lac salé des Gyséens",
        numéro : 184,
        element : "Foudre:8-Terre:2"
    ,
        logo : "../../assets/img/pet/Logo.png",
        detail : "../../assets/img/pet/Details.PNG",
},
    {
        nom : "Foudre symbiose",
        attribut : "Volant",
        type : "Symbiose",
        favori : "Aucun (avec une Dragon-Ball ou top 1 saison)",
        zone : "Lac salé des Gyséens",
        numéro : 185,
        element : "Foudre:8-Terre:2"
    ,
        logo : "../../assets/img/pet/Foudre symbioseLogo.png",
        detail : "../../assets/img/pet/Foudre symbioseDetails.PNG",
},
]
 


export default listFamiliers